### ISSUE TITLE
Segfault --oval-results

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#191] opened 2015-10-27 09:19 UTC
I have found some openscap segfault during work with openscap-daemon
```
$ oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_common --oval-results   /tmp/tmplTsI9g.txt 
```

I was suspecting my pullrequest https://github.com/OpenSCAP/openscap/pull/173, but when I revert its changes, problem is still here.

When I revert this commit https://github.com/OpenSCAP/openscap/commit/5a8295d4520f50aa2b23714e9d3809059666b8b1, problem disappear. BUT the wrong xml content should not be able to cause segfault, so the main problem is not in this content, but in openscap.

I have attached the content(Yes, it is xml, but with txt extension - github doesn't allow me to upload xml)
[tmplTsI9g.txt](https://github.com/OpenSCAP/openscap/files/21527/tmplTsI9g.txt)

Original content from https://github.com/OpenSCAP/openscap-daemon/blob/master/tests/data_dir_template/tasks/1.xml

```
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106		movdqu	(%rax), %xmm12
Missing separate debuginfos, use: dnf debuginfo-install nss-3.20.0-1.0.fc22.x86_64 pcre-8.37-4.fc22.x86_64
(gdb) where
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff7b4f82d in oval_state_to_dom (state=0x1128460, doc=0x12ea440, parent=0x132c590) at oval_state.c:344
#2  0x00007ffff7b43626 in oval_definition_model_to_dom (definition_model=0x10b5750, doc=0x12ea440, parent=<optimized out>)
    at oval_defModel.c:556
#3  0x00007ffff7b70aa6 in oval_results_to_dom (parent=0x0, doc=0x12ea440, directives_model=0x10b7710, results_model=0x10ba510)
    at oval_resModel.c:257
#4  oval_results_model_export_source (results_model=results_model@entry=0x10ba510, directives_model=directives_model@entry=0x0, 
    name=name@entry=0x12eb450 "/home/zmoravec/gitRepos/openscap/%2Fhome%2Fzmoravec%2FgitRepos%2Fopenscap%2Fcpe%2Fopenscap-cpe-oval.xml.result.xml") at oval_resModel.c:281
#5  0x00007ffff7b91a6f in _xccdf_session_export_oval_result_file (session=session@entry=0x61baf0, oval_session=<optimized out>)
    at xccdf_session.c:1115
#6  0x00007ffff7b93932 in _build_oval_result_sources (session=0x61baf0) at xccdf_session.c:1164
#7  xccdf_session_export_oval (session=session@entry=0x61baf0) at xccdf_session.c:1179
#8  0x000000000040b56c in app_evaluate_xccdf (action=0x7fffffffd540) at oscap-xccdf.c:500
#9  0x0000000000407d5e in oscap_module_call (action=0x7fffffffd540) at oscap-tool.c:260
#10 oscap_module_process (module=0x614480 <XCCDF_EVAL>, module@entry=0x613a00 <OSCAP_ROOT_MODULE>, argc=argc@entry=7, 
    argv=argv@entry=0x7fffffffd7c8) at oscap-tool.c:345
#11 0x0000000000406dff in main (argc=7, argv=0x7fffffffd7c8) at oscap.c:80


```

**Comment by jan-cerny** [comment] 2015-11-02 12:35
I can reproduce this on my machine. I will investigate this more.

**Comment by jan-cerny** [comment] 2015-11-02 17:27
This issue is a coincidence of multiple factors.

**First**, the commit 5a8295d4520f50aa2b23714e9d3809059666b8b1 really introduces an issue, because OVAL content in  cpe/openscap-cpe-oval.xml is invalid. When you try to validate it, you get
```
$ oscap oval validate openscap-cpe-oval.xml 
File 'openscap-cpe-oval.xml' line 596: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}object': No match found for key-sequence ['oval:org.open-scap.cpe.sled-release:obj:3'] of keyref '{http://oval.mitre.org/XMLSchema/oval-definitions-5}objectKeyRef'.
File 'openscap-cpe-oval.xml' line 601: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}object': No match found for key-sequence ['oval:org.open-scap.cpe.sled-release:obj:3'] of keyref '{http://oval.mitre.org/XMLSchema/oval-definitions-5}objectKeyRef'.
File 'openscap-cpe-oval.xml' line 556: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}state': No match found for key-sequence ['oval:org.open-scap.cpe.sles:ste:1'] of keyref '{http://oval.mitre.org/XMLSchema/oval-definitions-5}stateKeyRef'.
File 'openscap-cpe-oval.xml' line 561: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}state': No match found for key-sequence ['oval:org.open-scap.cpe.sled:ste:1'] of keyref '{http://oval.mitre.org/XMLSchema/oval-definitions-5}stateKeyRef'.
OpenSCAP Error: Invalid OVAL Definition (5.10.1) content in openscap-cpe-oval.xml. [oscap_source.c:205]
```
You can see that are referenced states that don't exist. This is first thing that needs to be fixed.

To avoid this in future, we have to create a test checking validity of this file and add this test to our upstream test suite.

**Second**, OpenSCAP segfaults when processing an invalid content, that doesn't contain referenced states. How to reproduce? Download this content: http://ur1.ca/o85l1 and the run:
```
 oscap oval eval --results results.xml --skip-valid test.xml
Definition oval:x:def:1: unknown
Evaluation done.
Segmentation fault (core dumped)
```

Backtrace
```
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff7b4ea65 in oval_family_to_namespace (family=<optimized out>, 
    schema_ns=0x7ffff7ba08d0 "http://oval.mitre.org/XMLSchema/oval-definitions-5", 
    doc=0x626020, parent=0x676160) at oval_enumerations.c:402
#2  0x00007ffff7b53cf0 in oval_state_to_dom (state=0x62be90, doc=0x626020, parent=0x676160)
    at oval_state.c:336
#3  0x00007ffff7b48776 in oval_definition_model_to_dom (definition_model=0x624730, 
    doc=0x626020, parent=<optimized out>) at oval_defModel.c:526
#4  0x00007ffff7b74416 in oval_results_to_dom (parent=0x0, doc=0x626020, 
    directives_model=0x7ffff7b74416 <oval_results_model_export+406>, results_model=0x627b80)
    at oval_resModel.c:251
#5  oval_results_model_export (results_model=results_model@entry=0x627b80, 
    directives_model=directives_model@entry=0x0, file=0x7fffffffdf58 "results.xml")
    at oval_resModel.c:279
#6  0x0000000000409a11 in app_evaluate_oval (action=0x7fffffffd8d0) at oscap-oval.c:445
#7  0x00000000004079be in oscap_module_call (action=0x7fffffffd8d0) at oscap-tool.c:261
#8  oscap_module_process (module=0x615000 <OVAL_EVAL>, 
    module@entry=0x6149c0 <OSCAP_ROOT_MODULE>, argc=argc@entry=7, 
    argv=argv@entry=0x7fffffffdb58) at oscap-tool.c:346
#9  0x00000000004069bf in main (argc=7, argv=0x7fffffffdb58) at oscap.c:79
```

I think this should be fixed in OpenSCAP. preferably in maint-1.0.

**Comment by isimluk** [comment] 2015-11-02 18:24
Good investigation, makes sense to me!

**Comment by jan-cerny** [comment] 2015-11-03 10:04
Pull request #207 solves the initiator. Zbyněk's use-case doesn't segfault anymore with that PR. However, the segfault is still possible with my use-case from my previous post. I am working on fixing it.

**Comment by jan-cerny** [comment] 2015-11-09 10:01
This issue should be fixed now.

**Closed by jan-cerny** 2015-11-09 10:01 UTC
Labels: bug
