### ISSUE TITLE
oscap isn't able to start due to locked file for verbose output

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#499] opened 2016-07-19 14:58 UTC
When I kill oscap (using ctrl+c) with verbose mode on e.g.

```
oscap oval eval --verbose DEVEL --verbose-log-file /tmp/c ./test_probes_file.xml 
```

I am not able to run oscap again. There is some file locking mechanism and lock on /tmp/c probably remains locked.

**Comment by mpreisler** [comment] 2016-07-19 15:13
I wonder if we are locking the file because we don't want other processes to access it or if we are locking the file to avoid writing to it from 2 threads inside openscap. If it's the latter we should use a mutex and not a file lock. That would solve the issue.

**Comment by ybznek** [comment] 2016-07-19 15:39
We don't have only threads, but processes - probes.

**Comment by mpreisler** [comment] 2016-07-19 15:52
Ah, so that's why.

/me goes for more coffee.

**Comment by ybznek** [comment] 2016-07-19 16:10
Maybe we could use semaphores - I am not sure about portability & behavior with chroot, I haven't used semaphores for years.

We could, at least, try to lock file during start of oscap and print message to stderr when file is already locked.

**Comment by radzy** [comment] 2016-10-31 22:50
I cannot duplicate this problem on WR Linux.  Does the error depend on the contents of test_probes_file.xml ?

**Comment by ybznek** [comment] 2016-11-30 11:04
@radzy 
I don't think so. Did you kill the oscap DURING its run?

**Comment by radzy** [comment] 2016-11-30 15:45
@ybznek : Yes, I killed it during the run.  I tried "several" times (but I don't remember how many that was).
How reproducible is it for you ?  Does it happen every time, or just once in a while ?
There's a possibility that there may be windows during which the dangling lock happens but that otherwise it doesn't, so reproducing it may take a few attempts.

**Comment by mpreisler** [comment] 2017-02-28 15:28
> We could, at least, try to lock file during start of oscap and print message to stderr when file is already locked.

+1

**Comment by jan-cerny** [comment] 2017-03-15 09:27
I am unable to reproduce this issue, although I tried it many times. I also noticed that when we open the file at the start and it already exists, we erase it, and we also check for return value of `open()` call. There is already an error message  See https://github.com/OpenSCAP/openscap/blob/maint-1.2/src/common/debug.c#L116

I wonder how this could happen. I suggest closing this.

**Closed** 2017-03-15 22:24 UTC
Labels: bug
