### ISSUE TITLE
[Bug] OpenSCAP doesn't support "state_operator" for tests

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/openscap#428] opened 2016-06-13 07:50 UTC
In [OVAL language specification](https://oval.mitre.org/language/version5.11/oval-language-specification_12-18-2014.pdf) (page 44, Section `4.3.12 TestType`) the purpose of OVAL's `state_operator` attribute for OVAL test is clarified:

```
state_operator  oval:OperatorEnumeration  0..1

Specifies how to logically combine the OVAL States referenced in the OVAL Test.
Default Value:  ‘AND’
```

Also from [`TestType` section of HTML documentation](https://oval.mitre.org/language/version5.11/ovaldefinition/documentation/oval-definitions-schema.html):

```
...
The optional state_operator attribute provides the logical operator that combines
the evaluation results from each referenced state on a per item basis. Each
matching item is compared to each referenced state. The result of comparing each
state to a single item is combined based on the specified state_operator value to
determine one result for each item. Finally, the results for each item are combined
based on the specified check value. Note that if the test does not contain any
references to OVAL States, then the state_operator attribute has no meaning and
can be ignored during evaluation. Referencing multiple states in one test allows
ranges of possible values to be expressed. For example, one state can check that
a value greater than 8 is found and another state can check that a value of less
than 16 is found. In this example the referenced states are combined with a
state_operator = 'AND' indicating that the conditions of all referenced states
must be satisfied and that the value must be between 8 AND 16. The valid
state_operation values are explained in the description of the
OperatorEnumeration simple type.
```

Now suppose the requirement to collect all `/etc/passwd` entries containing `/bin/bash` as shell, but only for UIDs >= 201 (SYS_UID_MIN) and <= 999 (SYS_UID_MAX). The requirement
also clarifies there shouldn't exist such UID (IOW count of UIDs from <201, 999> having shell set to `/bin/bash` is zero to meet the requirement):

Also suppose the following system configuration:

```
# grep bash /etc/passwd
root:x:0:0:root:/root:/bin/bash
iankko:x:1000:1000:Jan Lieskovsky:/home/iankko:/bin/bash
```

in other words this configuration meets the requirement (there isn't UID having shell set to
`/bin/bash` with UID in <201, 999> range).

Now take the following OVAL check (rename attached `oscap-state_operator-oval-test.txt` to `oscap-state_operator-oval-test.xml` and run `oscap oval eval` command on it):

[oscap-state_operator-oval-test.txt](https://github.com/OpenSCAP/openscap/files/311397/oscap-state_operator-oval-test.txt)

Current result:
## 

oscap doesn't support / recognize `state_operator` present in tests. The provided check
returns `false` because only one state is evaluated / counted into the final OVAL objects.

Expected result:
## 

oscap supports / recognizes the specific logical `state_operator` used in OVAL test (having one object and multiple tests). Based on that restricts the set of elements matching the requirement appropriately (in this case it will first take all UIDs => 201, then take all UIDs <= 999, and finally perform the `AND` operation between the collected objects to return the final set for textfilecontent54 object).

**Comment by iankko** [comment] 2016-06-13 13:55
Update #1: Partial issue from the testcase is above it doesn't pass the schematron:
```
# oscap oval validate --schematron oscap-state_operator-oval-test.xml 
<?xml version="1.0"?>
oval:x:tst:1 - No state should be referenced when check_existence has a value of 'none_exist'.
```

In any case removing the ```check_existence=none_exist``` part still doesn't work properly.

Checked with Tomas Heinrich, he suggests there might be issues with datatypes (the retrieved /etc/passwd UID field needs to be explicitly converted to int via intermediary variable_object). Will check that one yet. Stay tuned.

**Comment by matejak** [comment] 2018-08-01 14:58
This feature is an optional part of the OVAL specification. Therefore, this is not a bug, but a feature request.
I am closing it, but feel free to reopen it if a real-world use-case appears.

**Closed by matejak** 2018-08-01 14:58 UTC
Labels: bug, help wanted

**Comment by yuumasato** [comment] 2020-06-03 17:30
The `state_operator` actually works, and we even use in other definitions, like https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_set_max_sessions/oval/shared.xml#L40

**Comment by yuumasato** [comment] 2020-06-03 17:50
With [oscap-state_operator-oval-test-2.xml.txt](https://github.com/OpenSCAP/openscap/files/4725186/oscap-state_operator-oval-test-2.xml.txt), and oscap 1.3.3, I get following expected results:
```Definition oval:x:def:6: false
Definition oval:x:def:5: true
Definition oval:x:def:4: false
Definition oval:x:def:3: true
Definition oval:x:def:2: true
Definition oval:x:def:1: true
Evaluation done.

```
