### ISSUE TITLE
EL6 ssh ciphers false positve

### ISSUE THREAD

**Issue by matonb** [OpenSCAP/openscap#920] opened 2017-11-25 09:36 UTC
SCAP Workbench 1.1.5, compiled with Qt 4.8.7, using OpenSCAP 1.3.0

Failure:
` Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc # Logging`

sshd_config
```
Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc

# Logging
```

**Comment by dahaic** [comment] 2017-11-28 12:46
Hello @matonb, can you select only this one rule and attach/link `results.html`? Will help us with debugging.

Also to be sure, can you download latest SSG https://github.com/OpenSCAP/scap-security-guide/releases/tag/v0.1.36 and try to use that for scanning? We had some issues fixed regarding ciphers in past months.

Thanks for the report!

**Comment by matonb** [comment] 2017-11-28 22:59
I'll see if I can reproduce the issue, I don't have access to the particular server that had that fault anymore...

**Comment by matonb** [comment] 2017-12-06 09:25
@dahaic I've create a CentOS6 vm and can reproduce the issue using scap-workbench 1.1.5

How do I update the scap security guide on OS X? 

I'm guessing I need to unpack one or more of the zip files in the SSG link you referenced somewhere....

**Comment by yuumasato** [comment] 2017-12-06 09:56
@matonb Hello,

The zip file in SSG releases page is what you'll need.
https://github.com/OpenSCAP/scap-security-guide/releases/download/v0.1.36/scap-security-guide-0.1.36.zip

After downloading and unzipping, in Workbench you can select option to load Other SCAP Content, either in SCAP Security Guide content selector or in menu File option.

**Comment by matonb** [comment] 2017-12-06 10:56
I'm still seeing the false positive using v0.1.36, attached the single rule report as requested:

[ssh_cipers_el6.report.html.zip](https://github.com/OpenSCAP/openscap/files/1534870/ssh_cipers_el6.report.html.zip)

sshd_config lines around Ciphers:

```
ChallengeResponseAuthentication yes
Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
ClientAliveCountMax 0
```

**Comment by dahaic** [comment] 2017-12-06 17:54
@matonb, but `xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers` has one check, if the OS is certified. That means it will fail on CentOS regardless the configuration. Only RHEL6/7 is marked as certified, at the moment. Sorry for not telling you sooner, I have not realized this fact.

I'll close this issue - it is not a bug.

**Closed** 2017-12-06 17:56 UTC

**Comment by matonb** [comment] 2017-12-07 08:25
Any reason why the certified OS test can be dropped for CentOS ?

```
            <reference ref_id="sshd_use_approved_ciphers" source="ssg" />
          </ns3:metadata>
          <ns3:criteria operator="AND">
            <ns3:extend_definition comment="Installed OS is certified" definition_ref="oval:ssg-installed_OS_is_certified:def:1" />
            <ns3:criteria comment="SSH is not installed or conditions are met" operator="OR">
```

```
            <reference ref_id="sshd_use_approved_ciphers" source="ssg" />
          </ns3:metadata>
          <ns3:criteria operator="AND">
            <ns3:criteria comment="SSH is not installed or conditions are met" operator="OR">
```

**Comment by shawndwells** [comment] 2017-12-07 16:33
@matonb the ``sshd_use_approved_ciphers`` evaluates if the system is using FIPS validated crypto. CentOS does not have FIPS certification, so the rule appropriately fails on that platform.
