### ISSUE TITLE
oscap-chroot incorrectly evaluates tests containing filters and variables

### ISSUE THREAD

**Issue by praving55** [OpenSCAP/openscap#675] opened 2017-02-08 17:15 UTC
OpenSCAP Version - 1.2.13

Steps to reproduce:

1. Create a directory: `mkdir -p /tmp/chroot-test`
2. Create a file inside the directory: `touch /tmp/chroot-test/new-test1`
3. Enable SUID bit on the file: `chmod 4777 /tmp/chroot-test/new-test1`
4. Run the attached content which finds if there are any SUIDs using `oscap-chroot`. It evaluates to `true`. It should `fail`. If you run the same content using `oscap`, it evaluates perfect.
`sudo oscap-chroot chroot-test/ oval eval suid-check.xml`

Below is `suid-check.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<oval_definitions xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" 
	                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	                xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5" 
	                xmlns:oval-def="http://oval.mitre.org/XMLSchema/oval-definitions-5"
	                xmlns:linux-def="http://oval.mitre.org/XMLSchema/oval-definitions-5#linux"
	                xmlns:unix-def="http://oval.mitre.org/XMLSchema/oval-definitions-5#unix"	
	                xmlns:independent-def="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" 
	                xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-definitions-5 oval-definitions-schema.xsd http://oval.mitre.org/XMLSchema/oval-common-5 oval-common-schema.xsd http://oval.mitre.org/XMLSchema/oval-definitions-5#independent independent-definitions-schema.xsd http://oval.mitre.org/XMLSchema/oval-definitions-5#linux linux-definitions-schema.xsd http://oval.mitre.org/XMLSchema/oval-definitions-5#unix unix-definitions-schema.xsd">
  
  <generator>
    <oval:product_name>None</oval:product_name>
    <oval:product_version>None</oval:product_version>
    <oval:schema_version>5.11</oval:schema_version>
    <oval:timestamp>2017-02-04T12:32:41</oval:timestamp>
  </generator>

  <definitions>
    <definition id="oval:suid.test.com:def:1" 
                version="1" 
                class="compliance">
                <metadata>
                           <title>Ensure no SUID executables exist</title>
                           <description>This rule verifies that there are no SUID files.</description>
                </metadata>
                <criteria    operator="AND" 
                             negate="false" 
                             comment="none">

                  <criterion comment="none" 
                             test_ref="oval:suid.test.com:tst:1" />   
                </criteria>
    </definition>
  </definitions>
  	
  <tests>
     <file_test               xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#unix"
                              id="oval:suid.test.com:tst:1"
                              version="1"
                              check="all" 
                              comment="none"
                              check_existence="none_exist">
        <object               object_ref="oval:suid.test.com:obj:1" />
     </file_test>
   </tests>

   <objects>
    <file_object              xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#unix" 
                              id="oval:suid.test.com:obj:1" 
                              version="1" 
                              comment="none">
      <behaviors              recurse="directories" recurse_direction="down" max_depth="-1" recurse_file_system="local" />
      <path                   datatype="string" operation="equals">/</path>
      <filename               datatype="string" operation="pattern match">.*</filename>
    
      <filter                 xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5"
                              action="include">oval:suid.test.com:ste:1</filter>
    </file_object>
  </objects>
    
  <states>
    <file_state               xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#unix" 
                              id="oval:suid.test.com:ste:1" 
                              version="1" 
                              comment="none">
      <type                   datatype="string" operation="equals">regular</type>
      <suid                   datatype="boolean" operation="equals">1</suid>
    </file_state>
  </states>
</oval_definitions>
```

**Comment by mpreisler** [comment] 2017-02-08 18:30
Please paste output with `--verbose DEVEL`.

**Comment by praving55** [comment] 2017-02-08 18:43
```
ubuntu@ip-172-31-5-56:/tmp$ sudo oscap-chroot chroot-test/ oval eval --verbose DEVEL suid-check.xml
I: oscap: Identified document type: oval_definitions [oscap(10425):oscap(7fdeabc0c780):doc_type.c:93:oscap_determine_document_type_reader]
I: oscap: Created a new OVAL session from input file 'suid-check.xml'. [oscap(10425):oscap(7fdeabc0c780):oval_session.c:105:oval_session_new]
D: oscap: Validating OVAL Definition (5.11) document from suid-check.xml. [oscap(10425):oscap(7fdeabc0c780):oscap_source.c:321:oscap_source_validate]
I: oscap: No external OVAL variables provided. [oscap(10425):oscap(7fdeabc0c780):oval_session.c:281:oval_session_load_variables]
I: oscap: Started new OVAL agent. [oscap(10425):oscap(7fdeabc0c780):oval_agent.c:95:oval_agent_new_session]
D: oscap: __probe_meta_count = 41 [oscap(10425):oscap(7fdeabc0c780):oval_probe_session.c:135:oval_probe_session_init]
D: oscap: __probe_meta_count = 41 [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:997:oval_probe_ext_init]
D: oscap: skipped: filemd5 (stat failed, errno=2) [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:1006:oval_probe_ext_init]
D: oscap: skipped: sql (stat failed, errno=2) [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:1006:oval_probe_ext_init]
D: oscap: skipped: sql57 (stat failed, errno=2) [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:1006:oval_probe_ext_init]
D: oscap: skipped: inetlisteningserver (stat failed, errno=2) [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:1006:oval_probe_ext_init]
D: oscap: skipped: isainfo (stat failed, errno=2) [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:1006:oval_probe_ext_init]
D: oscap: skipped: process58 (stat failed, errno=2) [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:1006:oval_probe_ext_init]
D: oscap: skipped: fileextendedattribute (stat failed, errno=2) [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:1006:oval_probe_ext_init]
D: oscap: skipped: gconf (stat failed, errno=2) [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:1006:oval_probe_ext_init]
I: oscap: Querying system information. [oscap(10425):oscap(7fdeabc0c780):oval_probe.c:308:oval_probe_query_sysinfo]
I: oscap: Starting probe on URI 'pipe:///usr/libexec/openscap/probe_system_info'. [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:798:oval_probe_sys_handler]
D: oscap: Sending message. [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:493:oval_probe_comm]
D: oscap: MSG -> SEXP [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:261:SEAP_packet_msg2sexp]
D: oscap: ("seap.msg" ":id" 0 (("sysinfo_object" ":id" "sysinfo:0" ) ) ) [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:262:SEAP_packet_msg2sexp]
D: oscap: packet size: 376 [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:263:SEAP_packet_msg2sexp]
D: oscap: total I/O vectors = 1 [oscap(10425):oscap(7fdeabc0c780):strbuf.c:294:strbuf_write]
D: oscap: iot (1) < IOV_MAX (1024) [oscap(10425):oscap(7fdeabc0c780):strbuf.c:305:strbuf_write]
D: oscap: ioc = 1 [oscap(10425):oscap(7fdeabc0c780):strbuf.c:321:strbuf_write]
D: oscap: total bytes written: 67 [oscap(10425):oscap(7fdeabc0c780):strbuf.c:338:strbuf_write]
D: oscap: Waiting for reply. [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:552:oval_probe_comm]
D: probe_system_info: Signal handler ready [probe_system_info(10426):signal_handler(7f941ad98700):signal_handler.c:85:probe_signal_handler]
D: probe_system_info: icache worker ready [probe_system_info(10426):icache_worker(7f941b599700):icache.c:181:probe_icache_worker]
D: probe_system_info: return from select [probe_system_info(10426):input_handler(7f941a597700):seap-packet.c:637:SEAP_packet_recv]
D: probe_system_info: Received packet [probe_system_info(10426):input_handler(7f941a597700):seap-packet.c:902:SEAP_packet_recv]
D: probe_system_info: ("seap.msg" ":id" 0 (("sysinfo_object" ":id" "sysinfo:0" ) ) ) [probe_system_info(10426):input_handler(7f941a597700):seap-packet.c:903:SEAP_packet_recv]
D: probe_system_info: packet size: 477 [probe_system_info(10426):input_handler(7f941a597700):seap-packet.c:904:SEAP_packet_recv]
D: probe_system_info: offline_mode=00000001 [probe_system_info(10426):input_handler(7f941a597700):input_handler.c:116:probe_input_handler]
D: probe_system_info: offline_mode_supported=0000000f [probe_system_info(10426):input_handler(7f941a597700):input_handler.c:117:probe_input_handler]
D: probe_system_info: handling SEAP message ID 0 [probe_system_info(10426):probe_worker(7f9419b80700):worker.c:53:probe_worker_runfn]
D: probe_system_info: NOP [probe_system_info(10426):probe_worker(7f9419b80700):icache.c:404:probe_icache_nop]
I: probe_system_info: Extracting item from the cache queue: cnt=1, beg=0 [probe_system_info(10426):icache_worker(7f941b599700):icache.c:198:probe_icache_worker]
D: probe_system_info: Signaling `notfull' [probe_system_info(10426):icache_worker(7f941b599700):icache.c:217:probe_icache_worker]
D: probe_system_info: Handling cache request [probe_system_info(10426):icache_worker(7f941b599700):icache.c:248:probe_icache_worker]
D: probe_system_info: pair address: 140274090741360 [probe_system_info(10426):icache_worker(7f941b599700):icache.c:253:probe_icache_worker]
D: probe_system_info: item address: 140273833216800 [probe_system_info(10426):icache_worker(7f941b599700):icache.c:254:probe_icache_worker]
D: probe_system_info: item ID=10117250742137178835 [probe_system_info(10426):icache_worker(7f941b599700):icache.c:256:probe_icache_worker]
I: probe_system_info: cache MISS [probe_system_info(10426):icache_worker(7f941b599700):icache.c:262:probe_icache_worker]
D: probe_system_info: Signaling `notempty' [probe_system_info(10426):probe_worker(7f9419b80700):icache.c:429:probe_icache_nop]
D: probe_system_info: Waiting for icache worker to handle the NOP [probe_system_info(10426):probe_worker(7f9419b80700):icache.c:439:probe_icache_nop]
I: probe_system_info: Extracting item from the cache queue: cnt=1, beg=1 [probe_system_info(10426):icache_worker(7f941b599700):icache.c:198:probe_icache_worker]
D: probe_system_info: Signaling `notfull' [probe_system_info(10426):icache_worker(7f941b599700):icache.c:217:probe_icache_worker]
D: probe_system_info: Handling NOP [probe_system_info(10426):icache_worker(7f941b599700):icache.c:239:probe_icache_worker]
D: probe_system_info: Sync [probe_system_info(10426):probe_worker(7f9419b80700):icache.c:447:probe_icache_nop]
D: probe_system_info: old flag: 0, new flag: 2. [probe_system_info(10426):probe_worker(7f9419b80700):probe-api.c:686:probe_cobj_set_flag]
D: probe_system_info: handler result = 0x7f940c000a40, return code = 0 [probe_system_info(10426):probe_worker(7f9419b80700):worker.c:58:probe_worker_runfn]
D: probe_system_info: probe thread deleted [probe_system_info(10426):probe_worker(7f9419b80700):worker.c:77:probe_worker_runfn]
D: probe_system_info: Sorting blocks & building iterator array [probe_system_info(10426):probe_worker(7f9419b80700):sexp-manip.c:1402:SEXP_list_sort]
D: probe_system_info: Iterator count = 1 [probe_system_info(10426):probe_worker(7f9419b80700):sexp-manip.c:1429:SEXP_list_sort]
D: probe_system_info: cnt = 0 [probe_system_info(10426):probe_worker(7f9419b80700):seap-message.c:138:SEAP_msgattr_exists]
D: probe_system_info: no-reply not set: sending full reply [probe_system_info(10426):probe_worker(7f9419b80700):seap.c:480:SEAP_reply]
D: probe_system_info: MSG -> SEXP [probe_system_info(10426):probe_worker(7f9419b80700):seap-packet.c:261:SEAP_packet_msg2sexp]
D: probe_system_info: ("seap.msg" ":id" 0 ":reply-id" 0 (2 () ((("system_info_item" ":id" "1104261" ) ("os_name" "Unknown" ) ("os_version" "Unknown" ) ("os_architecture" "Unknown" ) ("primary_host_name" "Unknown" ) ) ) () ) ) [probe_system_info(10426):probe_worker(7f9419b80700):seap-packet.c:262:SEAP_packet_msg2sexp]
D: probe_system_info: packet size: 1304 [probe_system_info(10426):probe_worker(7f9419b80700):seap-packet.c:263:SEAP_packet_msg2sexp]
D: probe_system_info: total I/O vectors = 1 [probe_system_info(10426):probe_worker(7f9419b80700):strbuf.c:294:strbuf_write]
D: probe_system_info: iot (1) < IOV_MAX (1024) [probe_system_info(10426):probe_worker(7f9419b80700):strbuf.c:305:strbuf_write]
D: probe_system_info: ioc = 1 [probe_system_info(10426):probe_worker(7f9419b80700):strbuf.c:321:strbuf_write]
D: probe_system_info: total bytes written: 214 [probe_system_info(10426):probe_worker(7f9419b80700):strbuf.c:338:strbuf_write]
D: probe_system_info: name=reply-id, value=0x7f940c000b80 [probe_system_info(10426):probe_worker(7f9419b80700):seap-message.c:76:SEAP_msg_free]
D: oscap: return from select [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:637:SEAP_packet_recv]
D: oscap: Received packet [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:902:SEAP_packet_recv]
D: oscap: ("seap.msg" ":id" 0 ":reply-id" 0 (2 () ((("system_info_item" ":id" "1104261" ) ("os_name" "Unknown" ) ("os_version" "Unknown" ) ("os_architecture" "Unknown" ) ("primary_host_name" "Unknown" ) ) ) () ) ) [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:903:SEAP_packet_recv]
D: oscap: packet size: 1291 [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:904:SEAP_packet_recv]
D: oscap: Message received. [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:586:oval_probe_comm]
D: oscap: name=(null), value=0x1d24b10 [oscap(10425):oscap(7fdeabc0c780):seap-message.c:76:SEAP_msg_free]
I: oscap: OVAL agent started to evaluate OVAL definitions on your system. [oscap(10425):oscap(7fdeabc0c780):oval_agent.c:253:oval_agent_eval_system]
I: oscap: Evaluating definition 'oval:suid.test.com:def:1': Ensure no SUID executables exist. [oscap(10425):oscap(7fdeabc0c780):oval_resultDefinition.c:152:oval_result_definition_eval]
I: oscap:   Evaluating file test 'oval:suid.test.com:tst:1': none. [oscap(10425):oscap(7fdeabc0c780):oval_resultTest.c:1048:oval_result_test_eval]
I: oscap:     Querying file object 'oval:suid.test.com:obj:1', flags: 0. [oscap(10425):oscap(7fdeabc0c780):oval_probe.c:246:oval_probe_query_object]
I: oscap:     Creating new syschar for file_object 'oval:suid.test.com:obj:1'. [oscap(10425):oscap(7fdeabc0c780):oval_probe.c:269:oval_probe_query_object]
I: oscap:     Starting probe on URI 'pipe:///usr/libexec/openscap/probe_file'. [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:866:oval_probe_ext_handler]
I: oscap:     Object 'oval:suid.test.com:obj:1' has a filter that includes items conforming to state 'oval:suid.test.com:ste:1'. [oscap(10425):oscap(7fdeabc0c780):oval_sexp.c:544:oval_object_to_sexp]
D: oscap:     Sending message. [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:493:oval_probe_comm]
D: oscap:     MSG -> SEXP [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:261:SEAP_packet_msg2sexp]
D: oscap: ("seap.msg" ":id" 0 (("file_object" ":id" "oval:suid.test.com:obj:1" ":oval_version" "5.11" ) (("path" ":operation" 5 ":var_check" 1 ) "/" ) (("filename" ":operation" 11 ":var_check" 1 ) ".*" ) (("filter" ":action" 2 ) "oval:suid.test.com:ste:1" ) (("behaviors" ":recurse" "directories" ":recurse_direction" "down" ":max_depth" "-1" ":recurse_file_system" "local" ) ) ) ) [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:262:SEAP_packet_msg2sexp]
D: oscap:     packet size: 2253 [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:263:SEAP_packet_msg2sexp]
D: oscap:     total I/O vectors = 1 [oscap(10425):oscap(7fdeabc0c780):strbuf.c:294:strbuf_write]
D: oscap:     iot (1) < IOV_MAX (1024) [oscap(10425):oscap(7fdeabc0c780):strbuf.c:305:strbuf_write]
D: oscap:     ioc = 1 [oscap(10425):oscap(7fdeabc0c780):strbuf.c:321:strbuf_write]
D: oscap:     total bytes written: 406 [oscap(10425):oscap(7fdeabc0c780):strbuf.c:338:strbuf_write]
D: oscap:     Waiting for reply. [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:552:oval_probe_comm]
D: probe_file: icache worker ready [probe_file(10432):icache_worker(7f70d11cd700):icache.c:181:probe_icache_worker]
D: probe_file: Signal handler ready [probe_file(10432):signal_handler(7f70d09cc700):signal_handler.c:85:probe_signal_handler]
D: probe_file: return from select [probe_file(10432):input_handler(7f70d01cb700):seap-packet.c:637:SEAP_packet_recv]
D: probe_file: Received packet [probe_file(10432):input_handler(7f70d01cb700):seap-packet.c:902:SEAP_packet_recv]
D: probe_file: ("seap.msg" ":id" 0 (("file_object" ":id" "oval:suid.test.com:obj:1" ":oval_version" "5.11" ) (("path" ":operation" 5 ":var_check" 1 ) "/" ) (("filename" ":operation" 11 ":var_check" 1 ) ".*" ) (("filter" ":action" 2 ) "oval:suid.test.com:ste:1" ) (("behaviors" ":recurse" "directories" ":recurse_direction" "down" ":max_depth" "-1" ":recurse_file_system" "local" ) ) ) ) [probe_file(10432):input_handler(7f70d01cb700):seap-packet.c:903:SEAP_packet_recv]
D: probe_file: packet size: 2067 [probe_file(10432):input_handler(7f70d01cb700):seap-packet.c:904:SEAP_packet_recv]
D: probe_file: offline_mode=00000001 [probe_file(10432):input_handler(7f70d01cb700):input_handler.c:116:probe_input_handler]
D: probe_file: offline_mode_supported=00000001 [probe_file(10432):input_handler(7f70d01cb700):input_handler.c:117:probe_input_handler]
D: probe_file: handling SEAP message ID 0 [probe_file(10432):probe_worker(7f70cf7b4700):worker.c:53:probe_worker_runfn]
D: probe_file: code=1, args=0x7f70c0000980 [probe_file(10432):probe_worker(7f70cf7b4700):seap-command.c:248:SEAP_cmd_exec]
D: probe_file: EXEC_REMOTE [probe_file(10432):probe_worker(7f70cf7b4700):seap-command.c:311:SEAP_cmd_exec]
D: probe_file: CMD -> SEXP [probe_file(10432):probe_worker(7f70cf7b4700):seap-packet.c:440:SEAP_packet_cmd2sexp]
D: probe_file: ("seap.cmd" ":id" 0 ":class" "usr" ":type" "sync" 1 ("oval:suid.test.com:ste:1" ) ) [probe_file(10432):probe_worker(7f70cf7b4700):seap-packet.c:441:SEAP_packet_cmd2sexp]
D: probe_file: packet size: 471 [probe_file(10432):probe_worker(7f70cf7b4700):seap-packet.c:442:SEAP_packet_cmd2sexp]
D: probe_file: total I/O vectors = 1 [probe_file(10432):probe_worker(7f70cf7b4700):strbuf.c:294:strbuf_write]
D: probe_file: iot (1) < IOV_MAX (1024) [probe_file(10432):probe_worker(7f70cf7b4700):strbuf.c:305:strbuf_write]
D: probe_file: ioc = 1 [probe_file(10432):probe_worker(7f70cf7b4700):strbuf.c:321:strbuf_write]
D: probe_file: total bytes written: 92 [probe_file(10432):probe_worker(7f70cf7b4700):strbuf.c:338:strbuf_write]
D: oscap:     return from select [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:637:SEAP_packet_recv]
D: oscap:     Received packet [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:902:SEAP_packet_recv]
D: oscap: ("seap.cmd" ":id" 0 ":class" "usr" ":type" "sync" 1 ("oval:suid.test.com:ste:1" ) ) [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:903:SEAP_packet_recv]
D: oscap:     packet size: 529 [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:904:SEAP_packet_recv]
D: oscap:     code=1, args=0x1d27fa0 [oscap(10425):oscap(7fdeabc0c780):seap-command.c:248:SEAP_cmd_exec]
D: oscap:     EXEC_LOCAL [oscap(10425):oscap(7fdeabc0c780):seap-command.c:256:SEAP_cmd_exec]
D: oscap:     rec=0x1d24050, w=0 [oscap(10425):oscap(7fdeabc0c780):seap-command.c:284:SEAP_cmd_exec]
D: oscap:     res=0x1d28930 [oscap(10425):oscap(7fdeabc0c780):seap-command.c:293:SEAP_cmd_exec]
D: oscap:     func@(nil)(res)=0x1d28930 [oscap(10425):oscap(7fdeabc0c780):seap-command.c:299:SEAP_cmd_exec]
D: oscap:     CMD -> SEXP [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:440:SEAP_packet_cmd2sexp]
D: oscap: ("seap.cmd" ":id" 0 ":reply_id" 0 ":class" "usr" ":type" "async" 1 ((("file_state" ":id" "oval:suid.test.com:ste:1" ":operator" 1 ) (("type" ":operation" 5 ":var_check" 1 ":entity_check" 1 ":check_existence" 3 ) "regular" ) (("suid" ":operation" 5 ":var_check" 1 ":entity_check" 1 ":check_existence" 3 ) #T ) ) ) ) [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:441:SEAP_packet_cmd2sexp]
D: oscap:     packet size: 1858 [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:442:SEAP_packet_cmd2sexp]
D: oscap:     total I/O vectors = 1 [oscap(10425):oscap(7fdeabc0c780):strbuf.c:294:strbuf_write]
D: oscap:     iot (1) < IOV_MAX (1024) [oscap(10425):oscap(7fdeabc0c780):strbuf.c:305:strbuf_write]
D: oscap:     ioc = 1 [oscap(10425):oscap(7fdeabc0c780):strbuf.c:321:strbuf_write]
D: oscap:     total bytes written: 350D: probe_file:  [oscap(10425):oscap(7fdeabc0c780):strbuf.c:338:strbuf_write]
return from select [probe_file(10432):input_handler(7f70d01cb700):seap-packet.c:637:SEAP_packet_recv]
D: probe_file: Received packet [probe_file(10432):input_handler(7f70d01cb700):seap-packet.c:902:SEAP_packet_recv]
D: probe_file: ("seap.cmd" ":id" 0 ":reply_id" 0 ":class" "usr" ":type" "async" 1 ((("file_state" ":id" "oval:suid.test.com:ste:1" ":operator" 1 ) (("type" ":operation" 5 ":var_check" 1 ":entity_check" 1 ":check_existence" 3 ) "regular" ) (("suid" ":operation" 5 ":var_check" 1 ":entity_check" 1 ":check_existence" 3 ) #T ) ) ) ) [probe_file(10432):input_handler(7f70d01cb700):seap-packet.c:903:SEAP_packet_recv]
D: probe_file: packet size: 1988 [probe_file(10432):input_handler(7f70d01cb700):seap-packet.c:904:SEAP_packet_recv]
D: probe_file: code=0, args=0x7f70c8001850 [probe_file(10432):input_handler(7f70d01cb700):seap-command.c:248:SEAP_cmd_exec]
D: probe_file: EXEC_LOCAL [probe_file(10432):input_handler(7f70d01cb700):seap-command.c:256:SEAP_cmd_exec]
D: probe_file: rec=0x7f70c0000a20, w=1 [probe_file(10432):input_handler(7f70d01cb700):seap-command.c:284:SEAP_cmd_exec]
D: probe_file: res=(nil) [probe_file(10432):input_handler(7f70d01cb700):seap-command.c:293:SEAP_cmd_exec]
D: probe_file: func@(nil)(res)=(nil) [probe_file(10432):input_handler(7f70d01cb700):seap-command.c:299:SEAP_cmd_exec]
D: probe_file: cond return: h.args=0x7f70c8001850 [probe_file(10432):probe_worker(7f70cf7b4700):seap-command.c:433:SEAP_cmd_exec]
I: probe_file: Opening file '/'. [probe_file(10432):probe_worker(7f70cf7b4700):oval_fts.c:820:oval_fts_open]
E: probe_file: fsdev_init() failed. [probe_file(10432):probe_worker(7f70cf7b4700):oval_fts.c:850:oval_fts_open]
D: probe_file: NOP [probe_file(10432):probe_worker(7f70cf7b4700):icache.c:404:probe_icache_nop]
D: probe_file: Signaling `notempty' [probe_file(10432):probe_worker(7f70cf7b4700):icache.c:429:probe_icache_nop]
D: probe_file: Waiting for icache worker to handle the NOP [probe_file(10432):probe_worker(7f70cf7b4700):icache.c:439:probe_icache_nop]
I: probe_file: Extracting item from the cache queue: cnt=1, beg=0 [probe_file(10432):icache_worker(7f70d11cd700):icache.c:198:probe_icache_worker]
D: probe_file: Signaling `notfull' [probe_file(10432):icache_worker(7f70d11cd700):icache.c:217:probe_icache_worker]
D: probe_file: Handling NOP [probe_file(10432):icache_worker(7f70d11cd700):icache.c:239:probe_icache_worker]
D: probe_file: Sync [probe_file(10432):probe_worker(7f70cf7b4700):icache.c:447:probe_icache_nop]
D: probe_file: old flag: 0, new flag: 4. [probe_file(10432):probe_worker(7f70cf7b4700):probe-api.c:686:probe_cobj_set_flag]
D: probe_file: handler result = 0x7f70c0000d30, return code = 0 [probe_file(10432):probe_worker(7f70cf7b4700):worker.c:58:probe_worker_runfn]
D: probe_file: probe thread deleted [probe_file(10432):probe_worker(7f70cf7b4700):worker.c:77:probe_worker_runfn]
D: probe_file: Sorting blocks & building iterator array [probe_file(10432):probe_worker(7f70cf7b4700):sexp-manip.c:1402:SEXP_list_sort]
D: probe_file: Iterator count = 0 [probe_file(10432):probe_worker(7f70cf7b4700):sexp-manip.c:1429:SEXP_list_sort]
D: probe_file: cnt = 0 [probe_file(10432):probe_worker(7f70cf7b4700):seap-message.c:138:SEAP_msgattr_exists]
D: probe_file: no-reply not set: sending full reply [probe_file(10432):probe_worker(7f70cf7b4700):seap.c:480:SEAP_reply]
D: probe_file: MSG -> SEXP [probe_file(10432):probe_worker(7f70cf7b4700):seap-packet.c:261:SEAP_packet_msg2sexp]
D: probe_file: ("seap.msg" ":id" 0 ":reply-id" 0 (4 () () () ) ) [probe_file(10432):probe_worker(7f70cf7b4700):seap-packet.c:262:SEAP_packet_msg2sexp]
D: probe_file: packet size: 525 [probe_file(10432):probe_worker(7f70cf7b4700):seap-packet.c:263:SEAP_packet_msg2sexp]
D: probe_file: total I/O vectors = 1 [probe_file(10432):probe_worker(7f70cf7b4700):strbuf.c:294:strbuf_write]
D: probe_file: iot (1) < IOV_MAX (1024) [probe_file(10432):probe_worker(7f70cf7b4700):strbuf.c:305:strbuf_write]
D: probe_file: ioc = 1 [probe_file(10432):probe_worker(7f70cf7b4700):strbuf.c:321:strbuf_write]
D: probe_file: total bytes written: 51 [probe_file(10432):probe_worker(7f70cf7b4700):strbuf.c:338:strbuf_write]
D: oscap: D: probe_file:     name=reply-id, value=0x7f70c0000af0return from select [probe_file(10432):probe_worker(7f70cf7b4700):seap-message.c:76:SEAP_msg_free] [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:637:SEAP_packet_recv]

D: oscap:     Received packet [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:902:SEAP_packet_recv]
D: oscap: ("seap.msg" ":id" 0 ":reply-id" 0 (4 () () () ) ) [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:903:SEAP_packet_recv]
D: oscap:     packet size: 464 [oscap(10425):oscap(7fdeabc0c780):seap-packet.c:904:SEAP_packet_recv]
D: oscap:     Message received. [oscap(10425):oscap(7fdeabc0c780):oval_probe_ext.c:586:oval_probe_comm]
D: oscap:     name=(null), value=0x1d28880 [oscap(10425):oscap(7fdeabc0c780):seap-message.c:76:SEAP_msg_free]
I: oscap:     Test 'oval:suid.test.com:tst:1' requires that none of the objects defined by 'oval:suid.test.com:obj:1' exist on the system. [oscap(10425):oscap(7fdeabc0c780):oval_resultTest.c:816:_oval_result_test_evaluate_items]
I: oscap:     0 objects defined by 'oval:suid.test.com:obj:1' exist on the system. [oscap(10425):oscap(7fdeabc0c780):oval_resultTest.c:825:_oval_result_test_evaluate_items]
I: oscap:     Test 'oval:suid.test.com:tst:1' does not contain any state to compare object with. [oscap(10425):oscap(7fdeabc0c780):oval_resultTest.c:827:_oval_result_test_evaluate_items]
I: oscap:     No item matching object 'oval:suid.test.com:obj:1' was found on the system. (flag=does not exist) [oscap(10425):oscap(7fdeabc0c780):oval_resultTest.c:861:_oval_result_test_evaluate_items]
I: oscap:   Test 'oval:suid.test.com:tst:1' evaluated as true. [oscap(10425):oscap(7fdeabc0c780):oval_resultTest.c:1067:oval_result_test_eval]
I: oscap: Definition 'oval:suid.test.com:def:1' evaluated as true. [oscap(10425):oscap(7fdeabc0c780):oval_resultDefinition.c:163:oval_result_definition_eval]
Definition oval:suid.test.com:def:1: true
I: oscap: OVAL agent finished evaluation. [oscap(10425):oscap(7fdeabc0c780):oval_agent.c:283:oval_agent_eval_system]
I: oscap: OVAL evaluation successfully finished. [oscap(10425):oscap(7fdeabc0c780):oval_session.c:385:oval_session_evaluate]
Evaluation done.
D: probe_system_info: Received signal 15 from 10425 (parent) [probe_system_info(10426):signal_handler(7f941ad98700):signal_handler.c:100:probe_signal_handler]
D: probe_file: Received signal 15 from 10425 (parent) [probe_file(10432):signal_handler(7f70d09cc700):signal_handler.c:100:probe_signal_handler]
ubuntu@ip-172-31-5-56:/tmp$
```

**Comment by evgenyz** [comment] 2019-07-25 13:35
@matusmarhefka 

This bug does not exists in maint-1.3. Do we want to fix it for maint-1.2?

**Comment by matusmarhefka** [comment] 2019-07-26 07:27
@evgenyz I cannot reproduce it even on maint-1.2, I have tested on RHEL7:
```
# chmod 4777 chroot-test/new1
# ls -l chroot-test/
-rwsrwxrwx. 1 root root 0 Jul 26 03:20 new1
# oscap-chroot chroot-test/ oval eval suid-check.xml
Definition oval:suid.test.com:def:1: false
Evaluation done.
# chmod 0666 chroot-test/new1
# ls -l chroot-test/
-rw-rw-rw-. 1 root root 0 Jul 26 03:20 new1
# oscap-chroot chroot-test/ oval eval suid-check.xml
Definition oval:suid.test.com:def:1: true
Evaluation done.
```
Version of openscap used for the test:
`openscap-scanner-1.2.17-4.el7`
`openscap-1.2.17-4.el7`

**Comment by evgenyz** [comment] 2019-07-26 09:43
So, currently bug is not reproducible in both maint-1.2 and main-1.3. I'm closing it now. Feel free to reopen should it re-surface again.

**Closed by evgenyz** 2019-07-26 09:43 UTC
Labels: offline scan
