### ISSUE TITLE
Segmentation fault in selinuxboolean probe

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/openscap#487] opened 2016-07-12 18:01 UTC
`tests/probes/selinuxboolean`

```
TEST: test_probes_selinuxboolean-fail
OpenSCAP Error: Probe with PID=32222 has been killed with signal 11 [../../../../../src/OVAL/probes/SEAP/sch_pipe.c:173]
Probe with PID=32222 has core dumped. [../../../../../src/OVAL/probes/SEAP/sch_pipe.c:177]
Unable to close probe sd [../../../src/OVAL/oval_probe_ext.c:424]
Unable to receive a message from probe [../../../src/OVAL/oval_probe_ext.c:579]
RESULT: FAILED
```

```
Core was generated by `/home/jenkins/workspace/openscap-pull-requests/openscap-1.0.11/_build/src/OVAL/'.
Program terminated with signal 11, Segmentation fault.
#0  SEXP_ID_v_callback (sexp=0xabababababababab, pair=pair@entry=0x7f22f534ad40) at ../../../../../src/OVAL/probes/SEAP/sexp-ID.c:74
74          SEXP_val_dsc(&v_dsc, sexp->s_valp);
(gdb) where
#0  SEXP_ID_v_callback (sexp=0xabababababababab, pair=pair@entry=0x7f22f534ad40) at ../../../../../src/OVAL/probes/SEAP/sexp-ID.c:74
#1  0x00007f22fc98cc22 in SEXP_ID_v (s=<optimized out>) at ../../../../../src/OVAL/probes/SEAP/sexp-ID.c:110
#2  0x0000000000408220 in probe_icache_worker (arg=0xfe5670) at ../../../../../src/OVAL/probes/probe/icache.c:193
#3  0x00007f22fa4fbdc5 in start_thread (arg=0x7f22f534b700) at pthread_create.c:308
#4  0x00007f22f9e02ced in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by jan-cerny** [comment] 2016-07-14 10:32
We discussed this with @ybznek and @iankko. This problem is common for more probes, it often happens in file probe (see #447). Looks like a race condition of threads when accessing the icache. Hopefully #491 and #492 will help a bit.

**Comment by matusmarhefka** [comment] 2018-08-15 15:02
This issue is not reproducable anymore in upstream test suite, therefore closing.

**Closed by matusmarhefka** 2018-08-15 15:02 UTC
Labels: memory issues
