### ISSUE TITLE
OpenSCAP using reserved keyword `required` in C++20

### ISSUE THREAD

**Issue by ggbecker** [OpenSCAP/openscap#2084] opened 2024-02-13 10:24 UTC
During build in this PR in scap-workbench there is the follow:

https://github.com/OpenSCAP/scap-workbench/actions/runs/7884922384/job/21514950107?pr=302

```
In file included from /__w/scap-workbench/scap-workbench/include/APIHelpers.h:31,
                 from /__w/scap-workbench/scap-workbench/src/APIHelpers.cpp:22:
/usr/include/openscap/xccdf_benchmark.h:3346:90: error: identifier 'requires' is a keyword in C++20 [-Werror=c++20-compat]
 3346 | OSCAP_API bool xccdf_rule_add_requires(struct xccdf_rule *rule, struct oscap_stringlist *requires);
      |                                                                                          ^~~~~~~~
In file included from /__w/scap-workbench/scap-workbench/include/Scanner.h:32,
                 from /__w/scap-workbench/scap-workbench/include/MainWindow.h:26,
                 from /__w/scap-workbench/scap-workbench/src/Application.cpp:23:
/usr/include/openscap/xccdf_benchmark.h:3346:90: error: identifier 'requires' is a keyword in C++20 [-Werror=c++20-compat]
 3346 | OSCAP_API bool xccdf_rule_add_requires(struct xccdf_rule *rule, struct oscap_stringlist *requires);
      |                                                                                          ^~~~~~~~
In file included from /__w/scap-workbench/scap-workbench/build/scap-workbench_autogen/6YEA5652QU/../../../include/DiagnosticsDialog.h:31,
                 from /__w/scap-workbench/scap-workbench/build/scap-workbench_autogen/6YEA5652QU/moc_DiagnosticsDialog.cpp:10,
                 from /__w/scap-workbench/scap-workbench/build/scap-workbench_autogen/mocs_compilation.cpp:3:
/usr/include/openscap/xccdf_benchmark.h:3346:90: error: identifier 'requires' is a keyword in C++20 [-Werror=c++20-compat]
 3346 | OSCAP_API bool xccdf_rule_add_requires(struct xccdf_rule *rule, struct oscap_stringlist *requires);
      |                                                                                          ^~~~~~~~
cc1plus: all warnings being treated as errors
```

It seems that `requires` is a reserved word in some newer version of c++. The fix should be simple IMO.

**Comment by evgenyz** [comment] 2024-02-13 10:54
Duplicate of #1992

**Closed by evgenyz** 2024-02-13 10:54 UTC
Labels: bug
