### ISSUE TITLE
openscap compile problems on RHEL5 and SLES11

### ISSUE THREAD

**Issue by AndreasKrause** [OpenSCAP/openscap#408] opened 2016-05-03 06:32 UTC
When compiling openscap on RHEL5 or SLES11 problems occur with rpm related probes:

    [  313s]   CC       probe_rpminfo-rpminfo.o
    [  313s] In file included from unix/linux/rpminfo.c:63:
    [  313s] unix/linux/rpm-helper.h:77: error: expected declaration specifiers or '...' before 'rpmlogCallbackData'
    [  313s] unix/linux/rpminfo.c: In function 'probe_init':
    [  313s] unix/linux/rpminfo.c:275: warning: passing argument 1 of 'rpmlogSetCallback' from incompatible pointer type
    [  313s] unix/linux/rpminfo.c:275: error: too many arguments to function 'rpmlogSetCallback'
    [  313s] unix/linux/rpminfo.c: In function 'collect_rpm_files':
    [  313s] unix/linux/rpminfo.c:346: warning: implicit declaration of function 'rpmfiNew'
    [  313s] unix/linux/rpminfo.c:346: warning: assignment makes pointer from integer without a cast
    [  313s] unix/linux/rpminfo.c:348: warning: implicit declaration of function 'rpmfiNext'
    [  313s] unix/linux/rpminfo.c:350: warning: implicit declaration of function 'rpmfiFN'
    [  313s] unix/linux/rpminfo.c:350: warning: assignment makes pointer from integer without a cast
    [  313s] unix/linux/rpminfo.c:361: warning: implicit declaration of function 'rpmfiFree'
    [  313s] make[3]: *** [probe_rpminfo-rpminfo.o] Error 1
    [  313s] make[3]: Leaving directory `/usr/src/packages/BUILD/openscap-1.2.9/src/OVAL/probes'
    [  313s] make[2]: *** [all-recursive] Error 1
    [  313s] make[2]: Leaving directory `/usr/src/packages/BUILD/openscap-1.2.9/src/OVAL/probes'
    [  313s] make[1]: *** [all-recursive] Error 1
    [  313s] make[1]: Leaving directory `/usr/src/packages/BUILD/openscap-1.2.9'
    [  313s] make: *** [all] Error 2
    [  313s] error: Bad exit status from /var/tmp/rpm-tmp.20198 (%build)

Seems to be related to commits earlier this year (in April: https://github.com/OpenSCAP/openscap/commits/maint-1.2/src/OVAL/probes/unix/linux) when these probes were restructured.

**Comment by AndreasKrause** [comment] 2016-05-03 06:35
This issue could replace #393

**Comment by mpreisler** [comment] 2016-05-03 17:54
Consider using maint-1.0 - the 1.0.x branch on these older distributions.

**Comment by jan-cerny** [comment] 2016-05-12 13:07
@mpreisler Using maint-1.0 is not helpful here, because the changes in rpm probes affected the maint-1.0 probes as well. The same error messages appear when compiling maint-1.0 on RHEL5.

The problem seems to boil down to the fact that on new systems the `rpmLogSetCallback` is defined as:
`rpmlogCallback rpmlogSetCallback(rpmlogCallback cb, rpmlogCallbackData data)`
whereas on RHEL5 it is defined as:
`rpmlogCallback rpmlogSetCallback(rpmlogCallback cb);`
And in RHEL5 the  rpmlogCallbackData is not defined in rpm.

**Comment by mpreisler** [comment] 2016-05-12 20:31
This is a regression then, we need to track it down and fix it.

**Comment by jan-cerny** [comment] 2016-05-13 09:12
@mpreisler Definitely, this has to be fixed. We have received a lot of complaints about broken compilation on legacy systems in last weeks.

Is there a way how to check whether rpmlib is of version at least X.Y.Z by autotools? I have searched for it, browsed the official documentation, but I couldn't find anything. The problem is that this particular function exists in both old and new versions, but with a different prototype. Do we need to write a custom test in configure.ac? Or is there some easier way that I don't know? Thank you very much for your help.

**Comment by jan-cerny** [comment] 2016-05-17 08:54
Any thoughts?

**Comment by AndreasKrause** [comment] 2016-05-30 11:45
Since this issue is not tagged milestone 1.2.10 anymore, will I be forced to stick with maint-1.0?

**Comment by mpreisler** [comment] 2016-05-31 20:57
Hi @AndreasKrause. We will include the fix in both maint-1.0 and maint-1.2.

**Comment by jan-cerny** [comment] 2016-06-22 07:26
Fixed in https://github.com/OpenSCAP/openscap/pull/443

**Closed by jan-cerny** 2016-06-22 07:26 UTC
