### ISSUE TITLE
Test for selinuxboolean probe sometimes fails

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#288] opened 2016-01-11 15:24 UTC
Recently we have had failed builds on Fedora 23 and RHEL6 in Jenkins, as follows:

```
Making check in selinuxboolean
make[4]: Entering directory `/home/jenkins/workspace/openscap-maint/openscap-1.0.11/_build/tests/probes/selinuxboolean'
make  check-TESTS
make[5]: Entering directory `/home/jenkins/workspace/openscap-maint/openscap-1.0.11/_build/tests/probes/selinuxboolean'

----------------------------------------------------------------------
+ test_probes_selinuxboolean                                  [ PASS ]
+ test_probes_selinuxboolean-fail                             [ FAIL ]
--------------------------------------------------
See tests/probes/selinuxboolean/test_probes_selinuxboolean.log.

FAIL: test_probes_selinuxboolean.sh
==========================================
1 of 1 test failed
Please report to open-scap-list@redhat.com
==========================================
```

**Comment by jan-cerny** [comment] 2016-01-11 15:25
For example: https://jenkins.open-scap.org/job/openscap-maint/367/

**Comment by jan-cerny** [comment] 2016-01-18 09:49
Also on Fedora23, https://jenkins.open-scap.org/job/openscap-maint/379/

**Comment by jan-cerny** [comment] 2016-04-11 10:58
Recently we see this quite often on RHEL6 on Jenkins,
For example when testing PR #385 
https://jenkins.open-scap.org/job/openscap-pull-requests/435/consoleText

**Comment by mpreisler** [comment] 2016-12-06 19:53
@jan-cerny @rsprudencio Is this still an issue? I think this might have been fixed by Raphael and just not marked as such. Or is this a different issue?

**Comment by rsprudencio** [comment] 2016-12-07 13:16
Hard to say as the logs are gone, I think there is something going on because I saw a process58 probe failing last week. We're probably missing a race condition or a corner case somewhere.

**Comment by mpreisler** [comment] 2017-02-28 15:47
We cannot reproduce this any more. Most likely fixed by sexp memory fixes.

**Closed by mpreisler** 2017-02-28 15:47 UTC
