### ISSUE TITLE
oscap reports failure in some of the rules as "unknown"

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/openscap#761] opened 2017-06-23 11:23 UTC
Multiple rules behave this way, for example RHEL7 ```xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers```. Applied on fresh installation of RHEL7 (i.e. line is not present, but actually any failure of the rule reports as ```unknown```). Output with verbosity DEVEL attached.
[rule_sshd_use_approved_ciphers.verbose.txt](https://github.com/OpenSCAP/openscap/files/1097621/rule_sshd_use_approved_ciphers.verbose.txt)

Note: this is a regression against 1.2.14 version

**Comment by jan-cerny** [comment] 2017-06-23 12:37
This part looks interesting:

```
1143 I: oscap:       Evaluating systemdunitdependency test 'oval:ssg-test_multi_user_wants_sshd:tst:1':       systemd test. [oscap(31739):oscap(7f6f232b0840):oval_resultTest.c:1054:oval_result_test_eval]
1144 I: oscap:         Querying systemdunitdependency object 'oval:ssg-object_multi_user_target_for_sshd:     obj:1', flags: 0. [oscap(31739):oscap(7f6f232b0840):oval_probe.c:246:oval_probe_query_object]
1145 I: oscap:         Creating new syschar for systemdunitdependency_object 'oval:ssg-                       object_multi_user_target_for_sshd:obj:1'. [oscap(31739):oscap(7f6f232b0840):oval_probe.c:269:            oval_probe_query_object]
1146 I: oscap:         Test 'oval:ssg-test_multi_user_wants_sshd:tst:1' requires that zero or more            objects defined by 'oval:ssg-object_multi_user_target_for_sshd:obj:1' exist on the system.               [oscap(31739):oscap(7f6f232b0840):oval_resultTest.c:816:_oval_result_test_evaluate_items]
1147 I: oscap:         0 objects defined by 'oval:ssg-object_multi_user_target_for_sshd:obj:1' exist on       the system. [oscap(31739):oscap(7f6f232b0840):oval_resultTest.c:831:                                     _oval_result_test_evaluate_items]
1148 I: oscap:         No attempt was made to collect items matching object 'oval:ssg-                        object_multi_user_target_for_sshd:obj:1'. (flag=not collected) [oscap(31739):oscap(7f6f232b0840):        oval_resultTest.c:849:_oval_result_test_evaluate_items]
1149 I: oscap:       Test 'oval:ssg-test_multi_user_wants_sshd:tst:1' evaluated as unknown.                   [oscap(31739):oscap(7f6f232b0840):oval_resultTest.c:1073:oval_result_test_eval]
```

**Comment by jan-cerny** [comment] 2017-06-23 13:12
I think the reason is you haven't compiled the systemdunitdependency probe. This is not a bug or regression.

However, it's pretty hard to figure out that missing probe is reason of `content_rule_sshd_use_approved_ciphers`. From the first view SSHD configuration file has nothing in common with systemd. Even verbose mode doesn't help here much.

I suggest to improve the verbose mode. It could report a warning. It can be something like:
`Warning: Probe XYZ is needed to evaluate definition ABC, but it's not installed. Please compile OpenSCAP with probe XYZ.`

**Comment by jan-cerny** [comment] 2017-07-17 08:49
@dahaic Can we close this?

**Comment by jan-cerny** [comment] 2017-08-17 09:10
@dahaic I'll close this. If you experience the issue even after you compiled OpenSCAP with systemd probes, please reopen the issue an attach your configure log.

**Closed by jan-cerny** 2017-08-17 09:10 UTC

**Comment by DominiqueDevinci** [comment] 2019-10-12 21:30
@jan-cerny I experienced similar problem, you was right, after compliling with the correspondant probe enabled it's working (currently it's was OPENSCAP_PROBE_LINUX_SYSTEMDUNITDEPENDENCY which was disabled in the default package in debian9 repository). I will so enhance the debug info en link the PR to this issue.
