### ISSUE TITLE
Kernel Runtime Parameter IPv6 Check fails.   IPv6 is disabled via grub and sysctl.conf

### ISSUE THREAD

**Issue by pkbarbiedoll** [OpenSCAP/openscap#307] opened 2016-01-29 14:54 UTC
> oval:ssg:def:681 	**false** 	compliance 	[20141015], [sysctl_kernel_ipv6_disable] 	**Kernel Runtime Parameter IPv6 Check**

ipv6 is disabled per `/etc/sysctl.conf`

```
# NETWORK SECURITY
# Disable IPV6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

```

ipv6 is also disabled with kernel option in grub

```
# /etc/grub2.cfg
linux16 [mount opts] fips=1 rhgb quiet ipv6.disable=1
```

`lsmod` returns nothing on ipv6:

```
# lsmod | grep ipv6
# 

```

command used to generate report: 

`oscap oval eval --results $file_xml --report $file_html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

```
oscap --version
OpenSCAP command line tool (oscap) 1.2.5

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/share/openscap/schemas
Default CPE files: /usr/share/openscap/cpe
Probes: /usr/libexec/openscap

==== Inbuilt CPE names ====
Red Hat Enterprise Linux - cpe:/o:redhat:enterprise_linux
Red Hat Enterprise Linux 5 - cpe:/o:redhat:enterprise_linux:5
Red Hat Enterprise Linux 6 - cpe:/o:redhat:enterprise_linux:6
Red Hat Enterprise Linux 7 - cpe:/o:redhat:enterprise_linux:7
Community Enterprise Operating System 5 - cpe:/o:centos:centos:5
Community Enterprise Operating System 6 - cpe:/o:centos:centos:6
Community Enterprise Operating System 7 - cpe:/o:centos:centos:7
Scientific Linux 5 - cpe:/o:scientificlinux:scientificlinux:5
Scientific Linux 6 - cpe:/o:scientificlinux:scientificlinux:6
Scientific Linux 7 - cpe:/o:scientificlinux:scientificlinux:7
Fedora 16 - cpe:/o:fedoraproject:fedora:16
Fedora 17 - cpe:/o:fedoraproject:fedora:17
Fedora 18 - cpe:/o:fedoraproject:fedora:18
Fedora 19 - cpe:/o:fedoraproject:fedora:19
Fedora 20 - cpe:/o:fedoraproject:fedora:20
Fedora 21 - cpe:/o:fedoraproject:fedora:21
Fedora 22 - cpe:/o:fedoraproject:fedora:22
Fedora 23 - cpe:/o:fedoraproject:fedora:23
Red Hat Enterprise Linux Optional Productivity Applications - cpe:/a:redhat:rhel_productivity
Red Hat Enterprise Linux Optional Productivity Applications 5 - cpe:/a:redhat:rhel_productivity:5


```
OS version: 
```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

```

---------------------------------------------

**Comment by isimluk** [comment] 2016-02-01 07:38
@pkbarbiedoll , thanks for finding time for filing this.

This is not a bug of OpenSCAP, but the scap-security-guide ( https://github.com/OpenSCAP/scap-security-guide ).

I think this problem has been recently fixed by @redhatrises. See:
 * https://github.com/OpenSCAP/scap-security-guide/pull/988/files
 * https://github.com/OpenSCAP/scap-security-guide/pull/993/files

Please open new bug report at https://github.com/OpenSCAP/scap-security-guide/issues if you see your issue still not fixed by these commits. Thanks!

**Closed by isimluk** 2016-02-01 07:38 UTC

**Comment by pkbarbiedoll** [comment] 2016-02-01 19:31
@isimluk, thanks for clarification on where to file this issue.   

How frequently are updates pushed to clients through RHN?  I'm not showing any updates with yum update 

```
[user@machine ~]# yum info scap-security-guide

Installed Packages
Name        : scap-security-guide
Arch        : noarch
Version     : 0.1.25
Release     : 3.el7
Size        : 11 M
Repo        : installed
From repo   : rhel-7-server-rpms
Summary     : Security guidance and baselines in SCAP formats
URL         : https://github.com/OpenSCAP/scap-security-guide

[user@machine ~]# yum update scap-security-guide
No packages marked for update

```

**Comment by isimluk** [comment] 2016-02-03 13:04
Look @pkbarbiedoll, we don't disclose any information about when & what updates will arrive. This is mainly because the extensive testing is going on and the plans can change based on the testing. We basically do not want to disappoint customers by delivering an update, which may be on hold.

But to give you something useful, in history we have deliver new scap-security-guide package every minor RHEL update (that is RHEL-7.2, RHEL-6.7. RHEL-7.1, ...)

**Comment by pkbarbiedoll** [comment] 2016-02-03 15:19
Thank you.  Until the next version is released, I will continue documenting what I'm leaving "unfixed" to accompany the reports.
