### ISSUE TITLE
Non UTF-8 encoding in RPM verify when using --oval-results flag

### ISSUE THREAD

**Issue by nickfleming** [OpenSCAP/openscap#65] opened 2015-04-02 19:15 UTC
Using oscap 1.2.1 and running with the --oval-results flag the end of the scan report reports this error multiple times: 
````
/tmp/ssg-rhel7-oval.xml.result.xml:38166: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0xE1 0x3F 0x3B 0x10
            <lin-sys:filepath>▒?;</lin-sys:filepath>
                              ^
/tmp/ssg-rhel7-oval.xml.result.xml:38166: parser error : PCDATA invalid Char value 16
            <lin-sys:filepath>▒?;</lin-sys:filepath>
````
the application it's failing on is Security Center
In notepad++ the line looks like: 
````
<lin-sys:filepath>xE1?;DLExAE</lin-sys:filepath>
````
Other info:
OS: RHEL7.0
Command used (xxx are paths or names): oscap xccdf eval --profile xxx --cpe xxx --results xxx --oval-results --check-engine-results --report xxx xxx

**Comment by jan-cerny** [comment] 2016-06-22 15:03
This is most likely a duplicate of https://github.com/OpenSCAP/openscap/issues/212, which is already fixed. If you don't agree, feel free to reopen this.

**Closed by jan-cerny** 2016-06-22 15:03 UTC
