### ISSUE TITLE
Support OCIL document types

### ISSUE THREAD

**Issue by redhatrises** [OpenSCAP/openscap#397] opened 2016-04-21 15:28 UTC
When building with SSG, the following error is generated:

```OpenSCAP Error: Unknown document type: 'ssg-rhel6-ocil.xml' [oscap_source.c:148]```

See https://github.com/OpenSCAP/scap-security-guide/pull/1223

This error appears because it looks like the OCIL file format is not supported. OpenSCAP should support OCIL especially if it is being bundled with SSG.

**Comment by redhatrises** [comment] 2016-04-21 15:32
If this is a duplicate of #364, we can close this ticket.

**Comment by jan-cerny** [comment] 2016-04-22 07:55
Thank you very much @redhatrises for bringing this up.
Indeed, it is a duplicate of #364 . Closing this. The work on this issue will be tracked in #364 .

**Closed by jan-cerny** 2016-04-22 07:55 UTC
