### ISSUE TITLE
HTML Tags Displaying on OpenSCAP Evaluation Report

### ISSUE THREAD

**Issue by mears148** [OpenSCAP/openscap#500] opened 2016-07-19 15:38 UTC
When running DISA supplied SCAP benchmarks using OpenSCAP 1.2.8 on RHEL6 and 1.0.8 on RHEL5, I am seeing all HTML tags displayed in the evaluation reports, along with improper formatting such as spacing. Can anyone advise as to what may be happening here? Thanks. Here is an example...

> `<VulnDiscussion>All filesystems that are required for the successful operation of the system should be explicitly listed in "/etc/fstab" by an administrator. New filesystems should not be arbitrarily introduced via the automounter. The "autofs" daemon mounts and unmounts filesystems, such as user home directories shared via NFS, on demand. In addition, autofs can be used to handle removable media, and the default configuration provides the cdrom device as "/misc/cd". However, this method of providing access to removable media is not common, so autofs can almost always be disabled if NFS is not in use. Even if NFS is required, it is almost always possible to configure filesystem mounts statically by editing "/etc/fstab" rather than relying on the automounter. </VulnDiscussion><FalsePositives></FalsePositives><FalseNegatives></FalseNegatives><Documentable>false</Documentable><Mitigations></Mitigations><SeverityOverrideGuidance></SeverityOverrideGuidance><PotentialImpacts></PotentialImpacts><ThirdPartyTools></ThirdPartyTools><MitigationControl></MitigationControl><Responsibility></Responsibility><IAControls></IAControls>`<

**Comment by Mears148** [comment] 2016-07-19 16:46
I found another reference to the same issue that was closed a while back, but this may provide further clarification of the issue, as I am also seeing the usage of entities instead of real XML control characters in the DISA SCAP Benchmarks...

Here is the reference link: [https://fedorahosted.org/openscap/ticket/414#comment:2](url)

**Comment by mpreisler** [comment] 2016-07-19 17:32
Hi @Mears148,
as is explained in the fedorahosted.org ticket, these elements are DISA specific and don't hold any standard meaning. They aren't XHTML, HTML, SCAP, XCCDF or any other standard elements.

How do you propose we handle these? We could have special handling just for DISA benchmarks in OpenSCAP itself, if DISA is used so commonly that it makes sense to do so. Last time we looked into this we didn't think the issue is serious enough to warrant this.

**Comment by Mears148** [comment] 2016-07-20 13:49
I do believe this would help a good selection of the DoD community, which is a very important customer for OpenSCAP as a product, however, tackling this is something I wouldn't have much input on I'm afraid. I do know that the SCC product interprets DISA STIGs without the aforementioned issues being present, but I am not sure what handling measures are in place to do so. This may be a dead end issue, but if you, or anyone else for that matter, has any ideas, they would be greatly appreciated. My XML and HTML handling experience is limited, as I am more of a Puppet/Linux Engineer myself. Puppet is how I am deploying OpenSCAP in fact. Thanks.

**Comment by jan-cerny** [comment] 2016-08-02 11:11
@mpreisler Could we filter out (erase) everything which looks like a tag from the string that should be a plain text? Or maybe a better idea: What about leveraging those tags to show some nice colorful table (if course only when they're present)?

**Comment by mpreisler** [comment] 2016-08-02 14:05
> @mpreisler Could we filter out (erase) everything which looks like a tag from the string that should be a plain text? Or maybe a better idea: What about leveraging those tags to show some nice colorful table (if course only when they're present)?

I like the latter idea. We will have to do some XSLT magic to achieve it because they are essentially text thanks to the use of entities but it can be done.

**Comment by Mears148** [comment] 2016-08-04 13:43
Please let me know how I can help in all of this. If love to contribute in
any way I can. This will definitely help out DoD customers a great deal I'm
sure.

**Comment by jan-cerny** [comment] 2016-08-15 13:29
@Mears148 That would be cool :+1: To fix this particular issue it is necessary to play with XSLT templates located in the `xsl` directory. Those templates convert XML SCAP results into HTML. There would some place where those description are selected into the report. Most likely it would require to create a new `template` and implement the conversion of those tags.

**Comment by mpreisler** [comment] 2016-08-15 13:52
@Mears148 https://github.com/OpenSCAP/openscap/blob/maint-1.2/xsl/xccdf-share.xsl#L237 this "renders" the descriptions and other elements. To make this change you need to specialize this template just for cdf:description and implement the extra code for the formatting.

HTH!

**Comment by Mears148** [comment] 2016-08-16 14:17
@mpreisler That definitely gives me a place to start. I will see what I can come up with in my limited knowledge with XSLT templates. Thanks!

**Comment by evgenyz** [comment] 2020-04-24 11:52
Bug is not present in current stable (main-1.3) and master. Closing.

**Closed by evgenyz** 2020-04-24 11:52 UTC
